In [1]:
import pandas as pd

In [2]:
data = [20, 30, 40, 50]
series = pd.Series(data)
print(series)

0    20
1    30
2    40
3    50
dtype: int64


In [3]:
data = [1,3,5,7]
i = ['A', 'B', 'C', 'D']
series = pd.Series(data, index=i)
print(series)

A    1
B    3
C    5
D    7
dtype: int64


In [6]:
#create panda series using dictionary
data = {'v':10, 'jk':7, 'tk':30}
series = pd.Series(data)
print(series)

v     10
jk     7
tk    30
dtype: int64


In [7]:
series.replace(30,20)

v     10
jk     7
tk    20
dtype: int64

In [9]:
#create a series using numpy array
import numpy as np
data = np.array([200, 450, 600, 800])
series = pd.Series(data, index=['a','b','c','d'])
print(series)

a    200
b    450
c    600
d    800
dtype: int32


In [11]:
#create pandas dataframe from dictionary of lists
import pandas as pd
data = {'Name':['william','Archen','jk'], 'Age':[24,23,26], 'country':['US','Italy','SK']}
df = pd.DataFrame(data)
print(df)

      Name  Age country
0  william   24      US
1   Archen   23   Italy
2       jk   26      SK


In [14]:
#creating pandas dataframe from numpy arrays
import numpy as np
array = np.array([[3,5,6],[4,7,5],[7,8,4]])
print(array)
df = pd.DataFrame(array, columns=['A','B','C'])
print(df)

[[3 5 6]
 [4 7 5]
 [7 8 4]]
   A  B  C
0  3  5  6
1  4  7  5
2  7  8  4
